---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  test_repo_uri: https://github.com/TelekomLabs/tests-os-hardening.git

platforms:
#- name: ubuntu-12.04
#  driver_config:
#    box: ubuntu/precise64
#    box_url: https://atlas.hashicorp.com/ubuntu/boxes/precise64/versions/20150730.1.0/providers/virtualbox.box

#- name: ubuntu-14.04
#  driver_config:
#    box: ubuntu/trusty64
#    box_url: https://atlas.hashicorp.com/ubuntu/boxes/trusty64/versions/20150609.0.10/providers/virtualbox.box

#- name: centos-6.4
#  driver_config:
#    box: opscode-centos-6.4
#    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_centos-6.4_provisionerless.box

- name: centos-6.5
  driver_config:
    box: opscode-centos-6.5
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-6.5_chef-provisionerless.box

#- name: centos-7.1
#  driver_config:
#    box: opscode-centos-7.1
#    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-7.1_chef-provisionerless.box

#- name: oracle-6.4
#  driver_config:
#    box: oracle-6.4
#    box_url: https://storage.us2.oraclecloud.com/v1/istoilis-istoilis/vagrant/oel64-64.box

#- name: oracle-6.5
#  driver_config:
#    box: oracle-6.5
#    box_url: https://storage.us2.oraclecloud.com/v1/istoilis-istoilis/vagrant/oel65-64.box

#- name: debian-6
#  driver_config:
#    box: ffuenf/debian-6.0.10-amd64
#    box_url: https://atlas.hashicorp.com/ffuenf/boxes/debian-6.0.10-amd64/versions/1.0.11/providers/virtualbox.box

#- name: debian-7
#  driver_config:
#    box: debian/wheezy64
#    box_url: https://atlas.hashicorp.com/debian/boxes/wheezy64/versions/7.8.5/providers/virtualbox.box

#- name: debian-8
#  driver_config:
#    box: debian/jessie64
#    box_url: https://atlas.hashicorp.com/debian/boxes/jessie64/versions/8.1.0/providers/virtualbox.box

#verifier:
#  name: inspec

suites:
- name: default
  run_list:
  - recipe[os-hardening::default]

#- name: modules_disabled
#  run_list:
#  - recipe[os-hardening::default]
#  attributes:
#    security:
#      kernel:
#        enable_module_loading: false

